/*MODELAGEM DO BANCO DE DADOS*/
CREATE DATABASE IF NOT EXISTS REAL-STATE;

USE REAL-STATE;

CREATE TABLE IF NOT EXISTS TAB_USUARIOS(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(256) NOT NULL,
    STATUS INT NOT NULL,
    DATA_CRIACAO DATE
);

CREATE TABLE IF NOT EXIST TAB_ERROS(
    ID_ERRO INT PRIMARY KEY AUTO_INCREMENT,
    ERRO TEXT NOT NULL,
    ARQUIVO TEXT NOT NULL,
    LINHA INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    FK_USUARIO INT NOT NULL
);

/*CHAVES ESTRANGEIRAS*/
ALTER TABLE TBL_ERROS
ADD CONSTRAINT FK_USUARIO_ERRO
FOREIGN KEY (FK_USUARIO) REFERENCES TAB_USUARIOS(ID_USUARIO);
